// Define user roles
export enum UserRole {
  ADMIN = "ADMIN",
  CELL_LEADER = "CELL_LEADER",
  VILLAGE_LEADER = "VILLAGE_LEADER",
  ISIBO_LEADER = "ISIBO_LEADER",
  HOUSE_REPRESENTATIVE = "HOUSE_REPRESENTATIVE",
  CITIZEN = "CITIZEN",
}
