services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: communiserver-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - communiserver:/var/lib/postgresql/data
    networks:
      - communiserver

volumes:
  communiserver:

networks:
  communiserver:
